kind: Deployment
apiVersion: apps/v1
metadata:
  name: testapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: testapp
  template:
    metadata:
      labels:
        app: testapp
    spec:
      containers:
      - name: testapp
        readinessProbe: null
        livenessProbe:
          httpGet:
            path: /liveness-probe
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 15
        image: gcr.io/google_containers/echoserver:1.7
        resources:
          limits:
            memory: 512Mi
          requests:
            memory: 512Mi
        ports:
        - name: http-port
          containerPort: 8080
          protocol: TCP
        - name: https-port
          containerPort: 443
          protocol: TCP
