kind: Deployment
apiVersion: apps/v1
metadata:
  name: testapp-foo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: testapp-foo
  template:
    metadata:
      labels:
        app: testapp-foo
    spec:
      containers:
      - name: testapp-foo
        readinessProbe:
          httpGet:
            path: /readiness-probe
            port: 8080
          initialDelaySeconds: 15
          failureThreshold: 10
        image: gcr.io/google_containers/echoserver:1.7
        resources:
          limits:
            memory: 512Mi
          requests:
            memory: 512Mi
        ports:
        - name: http-port
          containerPort: 8080
          protocol: TCP
        - name: https-port
          containerPort: 443
          protocol: TCP
